data :
  name: MVTec3D  #MVTec #MTD #VisA 
  data_dir: datasets/MVTec3D  #MVTec #VisA #MTD  
  category: cable_gland  # ['bagel', 'cable_gland', 'carrot', 'cookie', 'dowel', 'foam', 'peach', 'potato', 'rope', 'tire']
  image_size: 256 
  batch_size: 1 # 32 # 32 for DDAD and 16 for DDADS (set 1 for debugging)
  DA_batch_size: 1 # 16 #16 for MVTec and [macaroni2, pcb1] in VisA, and 32 for other categories in VisA (set 1 for debugging)
  test_batch_size: 1 # 16 #16 for MVTec, 32 for VisA (set 1 for debugging) 
  mask : True 
  input_channel : 4  # 3RGB and 1 for depth map


model:
  DDADS: False  # DDAD small
  checkpoint_dir: checkpoints/MVTec3D   #MTD  #MVTec  #VisA
  checkpoint_name: weights
  exp_name: default
  feature_extractor: wide_resnet101_2 #wide_resnet101_2  # wide_resnet50_2 #resnet50
  learning_rate: 3e-4 
  weight_decay: 0.05
  epochs: 3000
  load_chp : 2000 # From this epoch checkpoint will be loaded. Every 250 epochs a checkpoint is saved. Try to load 750 or 1000 epochs for Visa and 1000-1500-2000 for MVTec.
  DA_epochs: 4 # Number of epochs for Domain adaptation.
  DA_chp: 4
  v : 1 #7 # 1 for MVTec and cashew in VisA, and 7 for VisA (1.5 for cashew). Control parameter for pixel-wise and feature-wise comparison. v * D_p + D_f
  w : 2 # Conditioning parameter. The higher the value, the more the model is conditioned on the target image. "Fine tuninig this parameter results in better performance".
  w_DA : 3 #3 # Conditioning parameter for domain adaptation. The higher the value, the more the model is conditioned on the target image.
  DLlambda : 0.1 # 0.1 for MVTec and 0.01 for VisA
  trajectory_steps: 1000
  test_trajectoy_steps: 250   # Starting point for denoising trajectory.
  test_trajectoy_steps_DA: 250  # Starting point for denoising trajectory for domain adaptation.
  skip : 25   # Number of steps to skip for denoising trajectory.
  skip_DA : 25
  eta : 1 # Stochasticity parameter for denoising process.
  beta_start : 0.0001
  beta_end : 0.02 
  device: 'cpu' # cuda #<"cpu", "gpu", "tpu", "ipu">
  save_model: True
  num_workers : 0 # 2, set 0 for debugging
  seed : 42


metrics:
  auroc: True
  pro: True
  misclassifications: False
  visualisation: False